// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aemhntbthjtldvlwntjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFlbWhudGJ0aGp0bGR2bHdudGp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4NjE1MDcsImV4cCI6MjA1NjQzNzUwN30.c9V6flLvAKDvx8KP4p3fYboTSPUwf-k983lNAonjFbA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);